version: '3.9'

services:
  db:
    image: timescale/timescaledb:latest-pg12
    # container_name: database_ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
  # app:
  #   build: .
  #   container_name: rentx
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   # network_mode: host
